apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "mlbench.name" . }}
    component: "{{ .Values.master.name }}"
    chart: {{ template "mlbench.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "mlbench.master.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets.apps", "statefulsets/status", "statefulsets.apps/status"]
  verbs: ["get", "list", "watch", "update", "patch"]